export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';

export const POST_NEWS_REQUEST = 'POST_NEWS_REQUEST';
export const POST_NEWS_SUCCESS = 'POST_NEWS_SUCCESS';
export const POST_NEWS_FAILURE = 'POST_NEWS_FAILURE';

export const NEWS_DETAILS_REQUEST = 'NEWS_DETAILS_REQUEST';
export const NEWS_DETAILS_SUCCESS = 'NEWS_DETAILS_SUCCESS';
export const NEWS_DETAILS_FAILURE = 'NEWS_DETAILS_FAILURE';

export const DELETE_NEWS = 'DELETE_NEWS';

export const FETCH_COMMENTS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_NEWS_FAILURE';

export const POST_COMMENT_REQUEST = 'POST_NEWS_REQUEST';
export const POST_COMMENT_SUCCESS = 'POST_NEWS_SUCCESS';
export const POST_COMMENT_FAILURE = 'POST_NEWS_FAILURE';

export const DELETE_COMMENT = 'DELETE_NEWS';